name: Deploy Backend to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  SERVICE_NAME: api-backend-solid
  ARTIFACT_REPOSITORY: api-backend-repo
  IMAGE_NAME: api-backend-solid

jobs:
  deploy:
    name: Build, Terraform and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Install backend dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/$IMAGE_NAME:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/$IMAGE_NAME:latest

      - name: Build Docker image notification-cloud-run
        run: |
          docker build \
            --platform linux/amd64 \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/notification-cloud-run:latest \
            ./notification-cloud-run

      - name: Push Docker image notification-cloud-run
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/notification-cloud-run:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan \
            -var="project_id=$PROJECT_ID" \
            -var="region=$REGION" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
            -var="smtp_email=${{ secrets.SMTP_EMAIL }}" \
            -var="smtp_password=${{ secrets.SMTP_PASSWORD }}" \
            -var="image_url=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/$IMAGE_NAME:latest"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="project_id=$PROJECT_ID" \
            -var="region=$REGION" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
            -var="smtp_email=${{ secrets.SMTP_EMAIL }}" \
            -var="smtp_password=${{ secrets.SMTP_PASSWORD }}" \
            -var="image_url=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/$IMAGE_NAME:latest"

      - name: Submit build with Cloud Build
        run: |
          gcloud builds submit \
            --tag $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/$IMAGE_NAME:latest \
            --async \
            --suppress-logs

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPOSITORY/$IMAGE_NAME:latest \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
            --min-instances 0 \ --max-instances 10